### PR TITLE
gradle update

### PR DESCRIPTION
**Pull request by hexosse**
I've added few task to simplify the process of creating library that can be shaded into other mod
+ gradle wrapper

### CODE REVIEW

**Comment by LoadingByte** [comment]
I don't quite get the universal library target. I know, it just creates a reobfuscated JAR without the mcmod file so that you can easily shade it into another mod. But doing such a shading is a very rare occurrence, and you need to relocate all the shaded files into a subpackage anyway in order to avoid collisions with a parallel properly installed library mod. So why bother about this extra JAR, when you could just shade and relocate the maven dependency, which would eliminate all your problems?

**Comment by hexosse** [comment]
This is because I don't have a maven repo so I store the jar in a local directory.
Then I use shadow plugin to relocate everything.
I could eventually remove the mcmod file when shading

**Comment by LoadingByte** [comment]
GuiLib is available through the QuarterCode repo. The exact steps on how to include it as a regular dependency are explained here: https://github.com/UnratedFilmIndustries/GuiLib/wiki/Installation

Adding shading in the build.gradle file of your mod shouldn't be that hard when you have already come this far. I think I even did some shading myself some time ago, I could try and find that project if you'd like me to.

**Comment by hexosse** [comment]
It's just that I might add few things to GuiLib and I don't want to depend on PR being accepted or not.
Just don't include the commit on build.gradle and I'll find an other way.
Don't bother

**Comment by LoadingByte** [comment]
Closing, since the 1.11.2 upgrade contains all these commits and has already been merged.

**Pull request closed without merging**
